os:
  - linux
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
sudo: true
env:
  - NODE_ENV=PROD
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - npm install
before_script:
  - npm run distribute
script:
  - npm run test-coveralls
  - npm run test-func
  - npm run lint
