environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '5'
    - nodejs_version: '6'
    - nodejs_version: '7'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set NODE_ENV=PROD
  - npm install
build: off
test_script:
  - npm test
